// Generated by https://quicktype.io

export class CreateListDto {
  name: string;
  description: string;
  language: string;

  constructor(n: string, d: string, l: string) {
    this.name = n;
    this.description = d;
    this.language = l;
  }
}
